# Generated by Django 4.0.5 on 2024-06-23 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StatusOfTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name="tasks",
            name="description",
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name="DescriptionOfTask",
        ),
    ]
