# Generated by Django 4.0.5 on 2024-06-23 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_statusoftask_alter_tasks_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasks",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="catalog.statusoftask"
            ),
        ),
    ]
