# Generated by Django 4.0.5 on 2024-06-28 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_remove_tasks_programmer_programmer_tasks"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="programmer",
            name="tasks",
        ),
        migrations.AddField(
            model_name="tasks",
            name="programmer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="catalog.programmer",
            ),
        ),
    ]
