# Generated by Django 4.0.5 on 2024-07-01 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_alter_programmer_groups_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasks",
            name="programmer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
